# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42bdbc6d247a603b7ae9b9f0a1e931796e7af6ddb1e1aed886468b5e87123b74aef1c29e91caa6bc39f43de4614543a43d6b9284cd948c998edef5d3f657803e

test:
  secret_key_base: ae38e542177f749fea0232b12d8d3ebbf2278041cfdfc2f58562f72c937ddebb60d5fec29c0ca6d806e7c0aea068bbdf602cc903a5585c8eeee7fd1905fe76b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
